import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { positionLabel } from '@/constants/positions';
import { Team, TeamBalanceMetrics } from '@/types/domain';

export async function generateAndShareTeamsPdf(teams: Team[], metrics: TeamBalanceMetrics) {
  const html = buildTeamsHtml(teams, metrics);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share team assignments' });
  }
  return uri;
}

export function buildTeamsHtml(teams: Team[], metrics: TeamBalanceMetrics) {
  const date = new Intl.DateTimeFormat('en-US', { dateStyle: 'long' }).format(new Date());
  const playerCount = teams.reduce((sum, team) => sum + team.players.length, 0);
  return `
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #17201c; margin: 36px; }
  h1 { color: #1e7a58; margin-bottom: 6px; }
  h2 { border-bottom: 2px solid #1e7a58; padding-bottom: 6px; margin-top: 28px; }
  .meta, .summary { background: #f4f2ea; border-radius: 8px; padding: 14px; margin: 18px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; page-break-inside: avoid; }
  th { text-align: left; background: #e5ebe6; }
  th, td { padding: 9px; border-bottom: 1px solid #d8ded9; }
  .footer { position: fixed; bottom: 18px; left: 36px; right: 36px; font-size: 11px; color: #68736d; }
</style>
</head>
<body>
  <h1>Volleyball Team Assignment</h1>
  <div class="meta">
    <strong>Date:</strong> ${date}<br />
    <strong>Teams:</strong> ${teams.length}<br />
    <strong>Players:</strong> ${playerCount}<br />
    <strong>Balance Score:</strong> ${metrics.overallBalanceScore} (${metrics.confidenceLabel})
  </div>
  ${teams.map(teamSection).join('')}
  <div class="summary">
    <h2>Team Skill Summary</h2>
    ${teams
      .map((team) => {
        const total = team.players.reduce((sum, player) => sum + player.ratingAtGeneration, 0);
        const avg = team.players.length ? (total / team.players.length).toFixed(2) : '0';
        return `<p><strong>${team.name}</strong><br />Total Skill: ${total}<br />Average: ${avg}</p>`;
      })
      .join('')}
  </div>
  <div class="footer">Generated by Volleyball Team Manager</div>
</body>
</html>`;
}

function teamSection(team: Team) {
  return `
  <h2>${team.name}</h2>
  <table>
    <thead><tr><th>Player</th><th>Position</th><th>Rating</th></tr></thead>
    <tbody>
      ${team.players
        .map(
          (player) =>
            `<tr><td>${escapeHtml(player.name)}</td><td>${positionLabel(player.positionAtGeneration)}</td><td>${'★'.repeat(player.ratingAtGeneration)}${'☆'.repeat(5 - player.ratingAtGeneration)}</td></tr>`
        )
        .join('')}
    </tbody>
  </table>`;
}

function escapeHtml(value: string) {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}
